const FETCH_SINGLE_SUCCESS = 'FETCH_SINGLE_SUCCESS';
const FETCH_ITEMS_ERROR = 'FETCH_ITEMS_ERROR';
const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
const FETCH_SINGLE_PENDING = 'FETCH_SINGLE_PENDING';
const FETCH_ITEMS_PENDING = 'FETCH_ITEMS_PENDING';
const CREATE_ITEM_PENDING = 'CREATE_ITEM_PENDING';

export {
  FETCH_ITEMS_ERROR,
  FETCH_ITEMS_PENDING,
  FETCH_SINGLE_SUCCESS,
  FETCH_ITEMS_SUCCESS,
  FETCH_SINGLE_PENDING,
  CREATE_ITEM_PENDING
};
